name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20.6" # Replace '1.x' with your desired Go version

      - name: Navigate to Go app directory
        run: cd apps/core
        run: ls
      - name: Build Go binary
        run: npm run build

  build-and-publish-node:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Navigate to Node.js app directory
        run: cd apps/cli

      - name: Install npm dependencies
        run: npm ci

      - name: Build Node.js package
        run: npm run build

      - name: Publish to npm
        run: npm run pub:glob
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
