name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6" # Replace '1.x' with your desired Go version

      - name: Navigate to Go app directory
        run: cd apps/core
      - name: ls
        run: ls
      - name: Build Go binary
        run: npm run build:core

  build-and-publish-node:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Navigate to Node.js app directory
        run: cd apps/cli

      - name: Install npm dependencies
        run: npm ci

      - name: Build Node.js package
        run: npm run build:cli
      - name: Authenticate with npm
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - name: Publish to npm
        run: cd apps/cli && npm run pub:cli
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
